# Generated by Django 3.1.5 on 2021-01-27 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_usersanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.choice'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
