# Generated by Django 3.1.5 on 2021-01-19 05:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usergrouop',
            new_name='Usergroup',
        ),
    ]
