# Generated by Django 3.1.5 on 2021-01-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20210119_0515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usergroup',
        ),
    ]
